### ISSUE TITLE
$.Model validators can't be used if superclass was created before loading validations.js

### ISSUE THREAD

**Issue by LazyDev2k** [jupiterjs/jquerymx#56]
$.Model validators can't be used if base class was created before loading validations.js.

Example:

[file x.js, steal('model.js')]: X extends $.Model. X doesn't use validations.
[file y.js, steal('x.js', 'validations.js')]: Y extends X. Y wants to use validations but can't do this because validations are injected into $.Model but not into classes already inherited from $.Model.

Explanation of event flow:
1. model.js is executed.
2. x.js  is executed. Class X doesn't contain methods like "validatePresenceOf" because validations.js is not loaded jet.
3. validations.js  is executed. Methods like "validatePresenceOf" injected into $.Model. Class X still doesn't have them.
4. y.js is executed. It attempts to access this.validatePresenceOf('...') but fails because this method only exists in $.Model.

**Comment by justinbmeyer** [comment]
Yeah, this is because static properties don't lookup on a prototype.  There's nothing that can really be done about this outside from stealing validations in the base class .... at least unless there is way to get a JS function who's proto does not point to Function.prototype.

This maybe a reason to to favor prototype construction like:

```
var inst = MyClass.create()
```

vs

```
var inst = new MyClass
```
